#!/bin/sh
### BEGIN INIT INFO
# Provides: esme-gpio26-toggle
# Required-Start: $remote_fs $time
# Required-Stop: $remote_fs $time
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: ESME GPIO#26 toggle service
### END INIT INFO

DAEMON=/usr/bin/esme-gpio-toggle
NAME=esme-gpio-toggle
PIDFILE=/var/run/$NAME.pid
ARGS="--gpio 26"

case "$1" in
    start)
        echo "Starting $NAME for GPIO#26..."
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $ARGS
        ;;
    stop)
        echo "Stopping $NAME for GPIO#26..."
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if start-stop-daemon --status --pidfile $PIDFILE; then
            PID=$(cat $PIDFILE)
            echo "Status of esme-gpio-toggle for GPIO#26: running with PID=$PID"
        else
            echo "Status of esme-gpio-toggle for GPIO#26: stopped"
        fi
        ;;
    *)
        echo "Usage: esme-gpio26-toggle (start | stop | restart | status)"
        exit 1
        ;;
esac

exit 0
